apiVersion: apps/v1
kind: Deployment
metadata:
  name: bastion
  namespace: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bastion
  template:
    metadata:
      labels:
        app: bastion
    spec:
      containers:
        - name: bastion
          image: nicolaka/netshoot
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
